apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nana
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nana
  template:
    metadata:
      labels:
        tier: frontend
        app: nana
    spec:
      containers:
      - name: my-cool-nginx
        image: omrisiri/nginx-hello:2.0
        env:
        - name: environment
          value: production
        resources:
          limits:
            cpu: 0.5
            memory: 200Mi
          requests:
            cpu: 0.1
            memory: 100Mi
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
